# Сообщения установленных значений
messages:
  minHeightMessage: "&7Сейчас установленная минимальная высота: &a"
  maxHeightMessage: "&7Сейчас установленная максимальная высота: &a"
  damageMessage: "&7Установленный урон от максимальной высоты: &a"
  periodMessage: "&7Установленный период наносимого урона в тиках: &a"

  # Сообщения при установке значений
  setMinHeightMessage: "&7Установлена новая минимальная высота: &a"
  setMaxHeightMessage: "&7Установлена новая максимальная высота: &a"
  setDamageMessage: "&7Установлен новый урон от максимальной высоты: &a"
  setPeriodMessage: "&7Новый период наносимого урона в тиках: &a"

  # Сообщение при неправильном указанном значении
  unknownCommandMessage: "Неправильное использование команды. /ac <аргумент> <значение>"

# Значения минимальной/максимальной высоты, наносимого урона, а также периода
minHeight: 100
maxHeight: 120
damage: 2.5

# Период урона указывается в тиках (1 тик = 1/20 секунды)
damagePeriod: 10
