messages:
  maxHeightMessage: "&7Сейчас установленная максимальная высота: &a"
  damageMessage: "&7Установленный урон от максимальной высоты: &a"

  setMaxHeightMessage: "&7Установлена новая максимальная высота: &a"
  setDamageMessage: "&7Установлен новый урон от максимальной высоты: &a"

  unknownCommandMessage: "Неправильное использование команды. /ac <аргумент> <значение>"

maxHeight: 120
damage: 2.5
